// ═══════════════════════════════════════════════════════════════════════════════
// MARKA VERİLERİ — MART 2026 TAM GÜNCELLEMESİ
//
// KAYNAKLAR:
// • World Coffee Portal (WCP) — espressolab.com global, caffenero.com.tr
// • Gıda Bülteni — kahve zincirleri şube sayıları (2025 güncel liste)
// • Aydınlık — Kahve Zinciri Savaşları 2025 güncel liste (Nis 2025)
// • Para Dergi — Dalga Dalga Büyüyen Pazar (Nis 2025)
// • Perfect Daily Grind — Specialty Coffee in Turkey (Mar 2026)
// • Greek City Times — Mikel Coffee Turkey (Eki 2025)
// • Ritapos.com — GUA Coffee başarı hikayesi (Ara 2025)
// • bayimolurmusun.com.tr — LUUQ, Laos franchise verileri
// • Forbes TR, Ekonomim, Horeca Trend
//
// ŞUBELERİN KAYNAĞI HER MARKADA branchSource ALANINDA BELİRTİLMİŞTİR.
// GELİR (annualRevenue) VERİLERİ TAHMİNÎDİR — doğrulanmış değildir.
// ═══════════════════════════════════════════════════════════════════════════════

export const BRANDS = [
  // ── KENDİ MARKAMIZ ──────────────────────────────────────────────────────────
  {
    id: 'espressolab',
    name: 'Espressolab',
    shortName: 'ESL',
    color: '#C4922A',
    bgColor: '#C4922A20',
    textColor: '#C4922A',
    founded: 2014,
    type: 'specialty',
    country: 'TR',
    isOwn: true,
    description: 'Türkiye\'nin en hızlı büyüyen specialty kahve zinciri — 18 ülkede 415+ şube',
    website: 'espressolab.com',
    instagram: '@espressolab',
    branches: 280,
    branchesGlobal: 415,
    avgPrice: 182,
    marketShare: 10,
    rating: 4.6,
    branchSource: 'Gıda Bülteni (2025): ~280 TR şube | Perfect Daily Grind Mar 2026: 415 global',
  },

  // ── BÜYÜK ZİNCİRLER ─────────────────────────────────────────────────────────
  {
    id: 'starbucks',
    name: 'Starbucks',
    shortName: 'SBX',
    color: '#00704A',
    bgColor: '#00704A20',
    textColor: '#00704A',
    founded: 1971,
    type: 'premium',
    country: 'US',
    isOwn: false,
    description: 'Avrupa\'da 2. büyük pazar — Alshaya Group (Shaya Kahve A.Ş.) operatörü',
    website: 'starbucks.com.tr',
    instagram: '@starbucksturkiye',
    branches: 685,
    avgPrice: 200,
    marketShare: 30,
    rating: 4.1,
    branchSource: 'Aydınlık / Gıda Bülteni (Nis 2025): 685 şube',
  },
  {
    id: 'kahvedunyasi',
    name: 'Kahve Dünyası',
    shortName: 'KD',
    color: '#8B1A1A',
    bgColor: '#8B1A1A20',
    textColor: '#E05050',
    founded: 2004,
    type: 'premium',
    country: 'TR',
    isOwn: false,
    description: 'Türkiye\'nin en büyük yerli zinciri — 500 şube hedefine ulaştı',
    website: 'kahvedunyasi.com',
    instagram: '@kahvedunyasi',
    branches: 500,
    avgPrice: 162,
    marketShare: 16,
    rating: 4.3,
    branchSource: 'Gıda Bülteni / Aydınlık (2025): 500 şube hedefine ulaşıldı',
  },
  {
    id: 'gloriajeans',
    name: 'Gloria Jean\'s',
    shortName: 'GJ',
    color: '#6B21A8',
    bgColor: '#6B21A820',
    textColor: '#A855F7',
    founded: 1979,
    type: 'premium',
    country: 'AU',
    isOwn: false,
    description: 'Avustralya kökenli — Dinçerler Group operatörü, 43+ ilde',
    website: 'gloriajeans.com.tr',
    instagram: '@gjcsturkey',
    branches: 200,
    avgPrice: 202,
    marketShare: 8,
    rating: 4.0,
    branchSource: 'Emlakkulisi.com (2025): 200+ şube, 43+ il | Aydınlık 2025 doğrulandı',
  },
  {
    id: 'sencay',
    name: 'Şen Çay Kahve',
    shortName: 'ŞÇK',
    color: '#15803D',
    bgColor: '#15803D20',
    textColor: '#4ADE80',
    founded: 2011,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'İzmir Bornova kökenli — Türk çay & kahve zinciri, 97 şube ulusal ağ',
    website: 'sencaykahve.com',
    instagram: '@sencaykahve',
    branches: 97,
    avgPrice: 80,
    marketShare: 2,
    rating: 4.0,
    branchSource: 'Gıda Bülteni (2025): 97 şube — 45 Ege, 31 Marmara bölgesi',
  },
  {
    id: 'arabica',
    name: 'Arabica Coffee House',
    shortName: 'ARB',
    color: '#854D0E',
    bgColor: '#854D0E20',
    textColor: '#D97706',
    founded: 2013,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'Türk markası — 47 ilde 170-180 şube, İstanbul\'da hızlı büyüme',
    website: 'arabicacoffeehouse.com',
    instagram: '@arabicacoffeehouse',
    branches: 200,
    avgPrice: 148,
    marketShare: 5,
    rating: 4.1,
    branchSource: 'Gıda Bülteni: ~170 (2024 sonu) | 2025 hedefi 230 → Mar 2026 tahmini: ~200',
  },
  {
    id: 'coffy',
    name: 'Coffy',
    shortName: 'CFY',
    color: '#D97706',
    bgColor: '#D9770620',
    textColor: '#FCD34D',
    founded: 2019,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'Jubilant FoodWorks (Hindistan) — 162 şube, %209 gelir artışı, hedef 350',
    website: 'coffy.com.tr',
    instagram: '@coffytr',
    branches: 200,
    avgPrice: 135,
    marketShare: 5,
    rating: 4.2,
    branchSource: '🔴 200. şube Ankara YHT Garı (25 Mar 2026) | WCP Tem 2025: 162 şube | Hedef: 350 şube',
  },
  {
    id: 'gua',
    name: 'GUA Coffee Company',
    shortName: 'GUA',
    color: '#B45309',
    bgColor: '#B4530920',
    textColor: '#F59E0B',
    founded: 2021,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'Türkiye\'nin ilk Bohem & Aztek konseptli kahvecisi — Gaziemir/İzmir, ~80 şube',
    website: 'guacoffeecompany.com',
    instagram: '@guacoffeecompany',
    branches: 80,
    avgPrice: 140,
    marketShare: 2,
    rating: 4.4,
    branchSource: 'Ritapos.com vaka çalışması (Ara 2025): ~80 şube, 40.000 günlük müşteri | 2024\'te 28 şube → 3x büyüme',
  },
  {
    id: 'luuq',
    name: 'LUUQ Coffee & Roastery',
    shortName: 'LUQ',
    color: '#7C3AED',
    bgColor: '#7C3AED20',
    textColor: '#A78BFA',
    founded: 2023,
    type: 'specialty',
    country: 'TR',
    isOwn: false,
    description: 'Marakeş ilhamlı specialty — Buca/İzmir, 78 şube 30 il + Fransa (kendi beyanı)',
    website: 'luuqcoffee.com',
    instagram: '@luuqcoffee',
    branches: 78,
    avgPrice: 155,
    marketShare: 2,
    rating: 4.5,
    branchSource: 'LUUQ Instagram biyografisi: 78 şube, 30 il, 2 ülke | bayimolurmusun.com.tr franchise listelemesi doğrulandı',
  },
  {
    id: 'caffenero',
    name: 'Caffè Nero',
    shortName: 'CN',
    color: '#1D4ED8',
    bgColor: '#1D4ED820',
    textColor: '#60A5FA',
    founded: 1997,
    type: 'premium',
    country: 'UK',
    isOwn: false,
    description: 'İtalyan tarzı — TR\'de %8 LFL büyüme (H1 FY26), yılda 30 yeni şube hedefi',
    website: 'caffenero.com.tr',
    instagram: '@caffeneroturkiye',
    branches: 120,
    avgPrice: 194,
    marketShare: 4,
    rating: 4.2,
    branchSource: '⚠️ Çelişkili kaynak: WCP May 2024: 95 şube (+30/yıl hedefi) → Mar 2026: ~120 | Gıda Bülteni: 45 şube (tarih belirsiz, muhtemelen eski)',
  },
  {
    id: 'laos',
    name: 'Laos Coffee Roastery',
    shortName: 'LCS',
    color: '#C2410C',
    bgColor: '#C2410C20',
    textColor: '#FB923C',
    founded: 2019,
    type: 'specialty',
    country: 'TR',
    isOwn: false,
    description: 'Antik Mısır temalı specialty & kavurma — İzmir kökenli, 32 ilde 62 şube',
    website: 'laoscoffeeroastery.com',
    instagram: '@laoscoffeeroastery',
    branches: 62,
    avgPrice: 150,
    marketShare: 2,
    rating: 4.3,
    branchSource: 'bayimolurmusun.com.tr haber (2025): "Türkiye\'nin en hızlı büyüyen kahve zincirlerinden biri, 32 ilde 62 şube"',
  },
  {
    id: 'brewmood',
    name: 'Brew Mood',
    shortName: 'BRM',
    color: '#0D9488',
    bgColor: '#0D948820',
    textColor: '#2DD4BF',
    founded: 2015,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'İzmir kökenli Türk zinciri — 22+ ilde 71+ şube',
    website: 'brewmood.com.tr',
    instagram: '@brewmoodcoffee',
    branches: 71,
    avgPrice: 145,
    marketShare: 2,
    rating: 4.1,
    branchSource: 'Gıda Bülteni / avmdergi.com (2025): 71 şube, 22+ il',
  },
  {
    id: 'coffeemania',
    name: 'Coffeemania',
    shortName: 'CMA',
    color: '#7E22CE',
    bgColor: '#7E22CE20',
    textColor: '#C084FC',
    founded: 2009,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'İzmir merkezli Türk zinciri — 61 TR + 5 uluslararası = 66 global',
    website: 'coffeemania.com.tr',
    instagram: '@coffeemania',
    branches: 61,
    avgPrice: 158,
    marketShare: 2,
    rating: 4.2,
    branchSource: 'Aydınlık (2025): 61 TR + 5 yurt dışı = 66 toplam',
  },
  {
    id: 'mikel',
    name: 'Mikel Coffee',
    shortName: 'MK',
    color: '#EA580C',
    bgColor: '#EA580C20',
    textColor: '#FB923C',
    founded: 1997,
    type: 'mid',
    country: 'GR',
    isOwn: false,
    description: 'Yunan kökenli — en büyük uluslararası pazarı TR, 6 günde 1 şube',
    website: 'mikelcoffee.com.tr',
    instagram: '@mikelcoffeetr',
    branches: 100,
    avgPrice: 153,
    marketShare: 3,
    rating: 4.0,
    branchSource: 'Greek City Times (Eki 2025: 87 şube, hedef 120) → Mar 2026: ~100',
  },
  {
    id: 'tchibo',
    name: 'Tchibo',
    shortName: 'TCH',
    color: '#92400E',
    bgColor: '#92400E20',
    textColor: '#F59E0B',
    founded: 1949,
    type: 'mid',
    country: 'DE',
    isOwn: false,
    description: 'Alman zinciri — Migros shop-in-shop + standalone, 5 yılda 100 şube hedefi',
    website: 'tchibo.com.tr',
    instagram: '@tchiboturkiye',
    branches: 62,
    avgPrice: 128,
    marketShare: 2,
    rating: 3.8,
    branchSource: 'Gıda Bülteni (Ağu 2025): 58. şube Ataşehir Metropol AVM\'de açıldı → Mar 2026: ~62',
  },
  {
    id: 'caribou',
    name: 'Caribou Coffee',
    shortName: 'CB',
    color: '#78350F',
    bgColor: '#78350F20',
    textColor: '#D97706',
    founded: 1992,
    type: 'premium',
    country: 'US',
    isOwn: false,
    description: 'Ülker Group — 14 ilde, yeni CEO Scott Kennedy (Eyl 2025)',
    website: 'cariboucoffee.com.tr',
    instagram: '@cariboucoffeetr',
    branches: 59,
    avgPrice: 212,
    marketShare: 2,
    rating: 4.3,
    branchSource: 'Aydınlık (Nis 2025): 59 şube, 14 il — konsolidasyon döneminde',
  },
  {
    id: 'nevada',
    name: 'Nevada Coffee',
    shortName: 'NV',
    color: '#0891B2',
    bgColor: '#0891B220',
    textColor: '#22D3EE',
    founded: 1996,
    type: 'mid',
    country: 'TR',
    isOwn: false,
    description: 'Nevco Holding (Ercan Narinç) — 38M$ global marka hakkı, uzun vade 500 hedefi',
    website: 'nevada.com.tr',
    instagram: '@nevadacafe',
    branches: 188,
    avgPrice: 118,
    marketShare: 3,
    rating: 3.9,
    branchSource: 'nevadacoffee.co/magazalarimiz (Mar 2026): 188 şube — İstanbul 100+, Ankara, Bursa, Trabzon + Karadağ (Podgorica, Budva)',
  },
  {
    id: 'kronotrop',
    name: 'Kronotrop',
    shortName: 'KR',
    color: '#059669',
    bgColor: '#05966920',
    textColor: '#34D399',
    founded: 2012,
    type: 'specialty',
    country: 'TR',
    isOwn: false,
    description: 'TR specialty öncüsü — Londra açıldı, no33 Coffee B2B, dünya şampiyonası',
    website: 'kronotrop.com',
    instagram: '@kronotrop',
    branches: 35,
    avgPrice: 183,
    marketShare: 1,
    rating: 4.7,
    branchSource: 'kronotrop.com.tr mağaza sayfası: İstanbul\'da çoklu şube (Cihangir, Moda, Bebek vb.) + Fact London Nis 2025',
  },
  {
    id: 'coffee1401',
    name: '1401 Coffee',
    shortName: '1401',
    color: '#0F766E',
    bgColor: '#0F766E20',
    textColor: '#2DD4BF',
    founded: 2022,
    type: 'specialty',
    country: 'TR',
    isOwn: false,
    description: 'İstanbul specialty — Düsseldorf\'ta ilk yurt dışı şube (2025), uluslararası genişleme',
    website: '1401coffee.com',
    instagram: '@1401coffee',
    branches: 20,
    avgPrice: 185,
    marketShare: 1,
    rating: 4.6,
    branchSource: 'Ekonomim (2025): ~20 TR şube, hedef 25 yıl sonu | Düsseldorf ilk int\'l şube açıldı',
  },
  {
    id: 'costacoffee',
    name: 'Costa Coffee',
    shortName: 'CC',
    color: '#7C2D12',
    bgColor: '#7C2D1220',
    textColor: '#F97316',
    founded: 1971,
    type: 'premium',
    country: 'UK',
    isOwn: false,
    description: '⚠️ Küresel #1 — Americana Group, TR operasyonları stratejik değerlendirmede',
    website: 'costacoffee.com.tr',
    instagram: '@costacoffeeturkiye',
    branches: 10,
    avgPrice: 219,
    marketShare: 1,
    rating: 4.1,
    branchSource: 'Para Dergi (Nis 2025): İstanbul, Antalya, Bodrum — ~7-12 şube | ⚠️ Küresel #1 ama TR\'de minimal varlık',
  },
];

export const BRAND_COLORS = BRANDS.reduce((acc, b) => { acc[b.id] = b.color; return acc; }, {});
export const BRAND_MAP    = BRANDS.reduce((acc, b) => { acc[b.id] = b;       return acc; }, {});
export const getBrand       = (id) => BRAND_MAP[id];
export const getOwnBrand    = ()   => BRANDS.find(b => b.isOwn);
export const getCompetitors = ()   => BRANDS.filter(b => !b.isOwn);
