import {
  LayoutDashboard,
  BarChart3,
  UtensilsCrossed,
  TrendingUp,
  Share2,
  Sparkles,
  Search,
  FileDown,
  Newspaper,
  MapPin,
  Building2,
  Monitor,
} from 'lucide-react';

export const NAV_ITEMS = [
  {
    path: '/',
    label: 'Ana Dashboard',
    labelShort: 'Dashboard',
    icon: LayoutDashboard,
    description: 'Genel bakış ve KPI\'lar',
  },
  {
    path: '/rakip-analizi',
    label: 'Rakip Analizi',
    labelShort: 'Rakipler',
    icon: BarChart3,
    description: 'Rakip marka karşılaştırması',
  },
  {
    path: '/menu-karsilastirmasi',
    label: 'Menü Karşılaştırması',
    labelShort: 'Menü',
    icon: UtensilsCrossed,
    description: 'Fiyat ve ürün karşılaştırması',
  },
  {
    path: '/satis-analizi',
    label: 'Satış Analizi',
    labelShort: 'Satışlar',
    icon: TrendingUp,
    description: 'Haftalık/aylık satış verileri',
  },
  {
    path: '/sosyal-medya',
    label: 'Sosyal Medya',
    labelShort: 'Sosyal',
    icon: Share2,
    description: 'Platform analizi ve takip',
  },
  {
    path: '/yeni-urun-radar',
    label: 'Yeni Ürün Radar',
    labelShort: 'Ürünler',
    icon: Sparkles,
    description: 'Rakip yeni ürün takibi',
  },
  {
    path: '/osint-raporlari',
    label: 'OSINT Raporları',
    labelShort: 'OSINT',
    icon: Search,
    description: 'Açık kaynak istihbaratı',
  },
  {
    path: '/son-dakika',
    label: 'Haber Akışı',
    labelShort: 'Haberler',
    icon: Newspaper,
    description: 'Canlı haber akışı & gelişmeler',
  },
  {
    path: '/sube-puanlari',
    label: 'Şube Puan Analizi',
    labelShort: 'Şubeler',
    icon: MapPin,
    description: 'Google Maps şube bazlı puanlar',
  },
  {
    path: '/gloria-jeans',
    label: "Gloria Jean's",
    labelShort: "GJ's",
    icon: Building2,
    description: "Gloria Jean's marka istihbaratı",
  },
  {
    href: 'https://gloriajeans.pulsaraai.com/admin/login',
    label: 'Müşteri Deneyimi Paneli',
    labelShort: 'MDP',
    icon: Monitor,
    description: 'Gloria Jean\'s müşteri deneyimi yönetimi',
    external: true,
  },
  {
    path: '/raporlar',
    label: 'Raporlar & Export',
    labelShort: 'Raporlar',
    icon: FileDown,
    description: 'Excel ve PPTX indirme',
  },
];
